In [2]:
from xbbbNN import visualize_pockets, get_xb_bb_positions, get_network_features, small_network_evaluation, head_on_network_evaluation, get_best_orientations, get_bb_head_on_model_features, get_bb_side_on_model_features

2024-01-26 09:29:32.067109: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-26 09:29:32.242636: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-26 09:29:32.755484: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-01-26 09:29:32.755575: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [3]:
from xbbbNN import get_bb_head_on_features_from_molecule, get_bb_side_on_features_from_molecule

In [4]:
import numpy as np

In [5]:
from xbpy import rdutil

In [6]:
model_system = next(rdutil.read_molecules("./structure_files/test_conformation.pdb"))

In [7]:
acceptor_atom = [atom for atom in model_system.GetAtoms() if atom.GetSymbol() == "O"][0]
halogen_atom = [atom for atom in model_system.GetAtoms() if atom.GetSymbol() in ["Cl", "Br", "I"]][0]
carbon_atom = [atom for atom in halogen_atom.GetNeighbors() if atom.GetSymbol() == "C"][0]

In [8]:
box_range = np.array([5.0]*3)
step_width = 0.5
def get_grid():
    bb_min, bb_max = - box_range, + box_range
    grid = np.mgrid[bb_min[0]:bb_max[0]:step_width, bb_min[1]:bb_max[1]:step_width, bb_min[2]:bb_max[2]:step_width]
    grid = grid.reshape(3, -1).T
    return grid

In [9]:
test_grid = np.array([[-1,-1,-1], [1,1,1]])

In [10]:
multi_features = get_bb_head_on_features_from_molecule(model_system, get_grid())
side_on_multi_features = get_bb_side_on_features_from_molecule(model_system, get_grid(), just_closest=True)

In [11]:
acceptor_positions = get_xb_bb_positions(acceptor_atom)
head_on_input, side_on_input = get_network_features(halogen_atom.GetSymbol(), rdutil.position(halogen_atom) + test_grid[0], rdutil.position(carbon_atom) + test_grid[0], acceptor_positions)
head_on_input, side_on_input

(array([ 1.75712291,  0.        , -0.9429922 ,  0.78135265,  0.94795662,
         0.93464928,  0.        ,  0.        ,  1.        ]),
 array([0.75712291, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.94795662, 0.96926151,
        0.93464928, 0.9858401 , 0.95199286, 0.83555463, 0.98614661,
        0.8009382 , 0.        , 0.        , 1.        ]))

In [12]:
from rdkit import Chem

In [13]:

head_on_input, side_on_input = get_network_features(halogen_atom.GetSymbol(), rdutil.position(halogen_atom) + test_grid[1], rdutil.position(carbon_atom) + test_grid[1], acceptor_positions)
head_on_input, side_on_input

(array([ 0.        ,  0.        , -0.97326019,  0.9692713 ,  0.96959988,
         0.99139629,  0.        ,  0.        ,  1.        ]),
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.96959988, 0.97824933,
        0.99139629, 0.95001369, 0.99375382, 0.97507138, 0.90763223,
        0.94601219, 0.        , 0.        , 1.        ]))

In [14]:
side_on_multi_features

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [15]:
np.cos(np.deg2rad(180 - 155.7))

0.9114032766354452

In [16]:
model_path = "/home/highgarden/Workspace/Thesis/XB_BB_Docking_Score/Data/Neural_Network/Weights/2,2,2-4,1-f2-it1"

In [17]:
import pymolviz as pmv
import numpy as np

In [18]:
import tensorflow as tf
import xbbbNN
tf.config.set_visible_devices([], 'GPU')
visible_devices = tf.config.get_visible_devices()
for device in visible_devices:
    assert device.device_type != 'GPU'

2024-01-26 09:29:37.058437: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-26 09:29:37.075381: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-26 09:29:37.075599: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2b:00.0/numa_node
Your kernel may have been built without NUMA support.


In [19]:
model = tf.keras.models.load_model(model_path, compile=False)

2024-01-26 09:29:37.296907: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [20]:
from xbpy import rdutil

In [21]:
multi_features.T.shape

(9, 8000)

In [22]:
prediction = model.predict([np.zeros((8000, 114)), np.zeros((8000, 1)), np.zeros((8000, 19)), multi_features], verbose=0)

In [23]:
head_on_prediction = prediction[:, 2]

In [24]:
get_grid() + rdutil.position(halogen_atom)

array([[ 1.228, -4.999, -4.998],
       [ 1.228, -4.999, -4.498],
       [ 1.228, -4.999, -3.998],
       ...,
       [10.728,  4.501,  3.502],
       [10.728,  4.501,  4.002],
       [10.728,  4.501,  4.502]])

In [25]:
import pymolviz as pmv
grid_data = pmv.GridData(head_on_prediction, get_grid() + rdutil.position(halogen_atom))
pmv.Volume(grid_data, name = "Head_on_prediction").write("head_on_prediction.py")

In [26]:
def direct_network_application(halogen_position, orientation, acceptor_atoms, halogen_symbol, bond_distance):
    head_on_predictions = [0.0]
    side_on_predictions = [0.0]
    for acceptor_atom in acceptor_atoms:
            try:
                acceptor_positions = get_xb_bb_positions(acceptor_atom)
            except IndexError:
                continue
            carbon_position = halogen_position - (orientation * bond_distance)
            head_on_input, side_on_input = get_network_features(halogen_symbol, halogen_position, carbon_position, acceptor_positions)
            prediction = model.predict([np.zeros((1, 114)), np.zeros((1, 1)), side_on_input.reshape(1, 19), head_on_input.reshape(1, 9)], verbose=0)
            side_on_predictions.append(prediction[0][1])
            head_on_predictions.append(prediction[0][2])
    return np.max(head_on_predictions)
            

In [27]:
pocket = rdutil.get_binding_pockets_by_ligand(next(rdutil.read_molecules("5nkd.pdb", proximityBonding=True)))[0]

In [28]:
all_detected = []
for oxygen in pocket.pocket_atoms:
    if not oxygen.GetSymbol() == "O":
        continue
    try:
        positions = get_xb_bb_positions(oxygen)
        #print(oxygen.GetIdx())
        all_detected.append(pmv.Points(positions, color = ["O", "C", "C", "H", "N", "H", "C", "H"], name = f"O{oxygen.GetIdx()}"))
    except:
        continue

pmv.Group(all_detected, name = "detected_acceptors").write("detected_acceptors.py")

In [29]:
backbone_system = rdutil.read_molecules("backbone.pdb", proximityBonding=True)[0]

TypeError: 'generator' object is not subscriptable

In [30]:
backbone_center = rdutil.position(list(backbone_system.GetAtoms())).mean(axis = 0)
backbone_center

NameError: name 'backbone_system' is not defined

In [ ]:
grid = [(x, y, z) for x in np.arange(-8, 8, .5) for y in np.arange(-8, 8, .5) for z in np.arange(-8, 8, .5)]
grid = np.array(grid)
#grid = grid[np.linalg.norm(grid, axis = 1) > 2]

grid = np.array(grid) + backbone_center
arrows, best_scores = get_best_orientations(grid, head_on_network_evaluation, "Cl", 1.7, [a for a in backbone_system.GetAtoms() if a.GetSymbol() == "O"])
labels = {}
acceptor_positions = get_xb_bb_positions([a for a in backbone_system.GetAtoms() if a.GetSymbol() == "O"][0])
for arrow  in arrows:
    orientation = (arrow[1] - arrow[0]) * 3.4
    features, _ = get_network_features("Cl", arrow[1], arrow[1] - orientation, acceptor_positions)
    for i, feature in enumerate(features):
        if not i in labels:
            labels[i] = []
        labels[i].append(f"{feature:.2f}")
arrows = np.array(arrows); best_scores = np.array(best_scores)
label_names = ["XO", "XN", "Acc_O", "Acc_N", "X_O", "X_N", "Cl", "Br", "I"]
for key in labels:
    labels[key] = pmv.Labels(arrows[:, 1], np.array(labels[key]), name = f"labels_{label_names[key]}")
pseudo_atoms = pmv.PseudoAtoms(arrows[:,0], best_scores, name=f"BB_PseudoAtoms")
arrows = pmv.Arrows(arrows, color = best_scores, name = f"BB_Arrows", linewidth=0.05, head_length=0.6)    
pmv.Group([arrows, arrows.colormap], name = f"BB_Group_faulty").write("backbone_system_faulty.py")

100%|██████████| 32768/32768 [00:51<00:00, 638.48it/s] 


(7230, 3) (7230, 3) (7230, 3)


In [ ]:
test_coords =[ 6.158642,  -2.8019161, -0.8649455]
from xbpy import geometry
cone = geometry.sample_cone(np.array([ 0, 0, 1]), 1, np.pi, 0.5)
scores = head_on_network_evaluation(test_coords, cone, [a for a in backbone_system.GetAtoms() if a.GetSymbol() == "O"], "Cl", 1.7)
pmv.Points(-cone + test_coords, color = scores.flatten(), name = "cone").write("cone.py")


In [ ]:
test_coords =[ 6.158642,  -2.8019161, -0.8649455]
from xbpy import geometry
best_direction = cone[np.argmin(scores)]; best_direction /= np.linalg.norm(best_direction)
cone = geometry.sample_cone(best_direction, 1, np.pi/8, 0.1)
scores = head_on_network_evaluation(test_coords, cone, [a for a in backbone_system.GetAtoms() if a.GetSymbol() == "O"], "Cl", 1.7)
pmv.Points(-cone + test_coords, color = scores.flatten(), name = "cone_tightened").write("cone_tightened.py")



In [ ]:
cone[np.argmin(scores)]

array([ 0.75086239, -0.6147601 , -0.24140357])

In [ ]:
scores.shape
cone = geometry.sample_cone([1, 0, 0], 1, np.pi/8, 0.1)
pmv.Points(cone, color = "red", name = "cone_test").write("cone_test.py")


In [ ]:

#visualize(direct_network_application, "5nkd.pdb").write("direct_head_on_test.py")
visualize_pockets(head_on_network_evaluation, "5nkd.pdb").write("head_on_test_faulty.py")

100%|██████████| 1720/1720 [01:40<00:00, 17.15it/s]


(170, 3) (170, 3) (170, 3)
